# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\xortest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.combo_x = QtWidgets.QComboBox(self.centralwidget)
        self.combo_x.setGeometry(QtCore.QRect(60, 110, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.combo_x.setFont(font)
        self.combo_x.setObjectName("combo_x")
        self.combo_x.addItem("")
        self.combo_x.addItem("")
        self.combo_y = QtWidgets.QComboBox(self.centralwidget)
        self.combo_y.setGeometry(QtCore.QRect(400, 110, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.combo_y.setFont(font)
        self.combo_y.setObjectName("combo_y")
        self.combo_y.addItem("")
        self.combo_y.addItem("")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(260, 290, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 230, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.submit_button.clicked.connect(self.pressed)

        # # Add item to combo box
        # self.combo_x.addItem("Hello")
        # # set default item
        # index = self.combo_x.findText("Hello", QtCore.Qt.MatchFixedString)
        # self.combo_x.setCurrentIndex(index) # This index will be default selected

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def pressed(self):
        x = int(self.combo_x.currentText())
        y = int(self.combo_y.currentText())

        xor = (x and not y) or (y and not x)
        if xor == True:
            xor = 1
        else:
            xor = 0
        self.label.setText("X XOR Y = " + str(xor))
        self.label.adjustSize()


    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.combo_x.setItemText(0, _translate("main_window", "0"))
        self.combo_x.setItemText(1, _translate("main_window", "1"))
        self.combo_y.setItemText(0, _translate("main_window", "0"))
        self.combo_y.setItemText(1, _translate("main_window", "1"))
        self.submit_button.setText(_translate("main_window", "Submit"))
        self.label.setText(_translate("main_window", "X XOR Y ="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
